#!/bin/bash
#
# When adding (or removing) any functions remember to update
# the 'install_thirdparty' function below to reflect any changes you make

# Automatically import apps functions
function import_apps_functions {
	DIR="functions/apps"
	# iterate through the files in the 'functions/apps' folder
	for FUNCTION in ${SCRIPT_DIR}/$DIR/*; do
		if [[ -d $FUNCTION ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
			. $FUNCTION
		fi
	done
}

# Install Third-Party Applications
function install_thirdparty {
	NAME="Third-Party Software"
	echo_message title "Starting installation of ${NAME,,}..."
	import_apps_functions
	# Draw window
	THIRDPARTY=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhat ${NAME,,} would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'install_chrome'        'Google Chrome' \
		'install_dropbox'       'Dropbox' \
		'install_oracle_java'   'Oracle Java' \
		'install_rvm'           'Ruby Version Manager (RVM)' \
		'install_sublime_text'  'Sublime Text 3' \
		'install_emacs'         'Emacs & helm' \
		'configure_emacs'       'Configure Emacs & helm' \
		'install_i3'            'i3 window manager' \
		'configure_i3'          'Configure i3 window manager' \
		'install_fzf'           'fzf fuzzy finder' \
		'install_citx'          'Install japanese keyboard' \
                'install_firefox'       'Install firefox' \
                'configure_firefox'     'Adjust firefox to i3' \
                'install_global'        'Install GNU global' \
                'install_python'        'Install Python' \
                'install_ietf_tools'    'Install IETF martinthomson requirements' \
                'configure_bash    '    'Creating/extend .bash_aliases' \
                'install_docker    '    'Install latest stable docker from docker apt repository' \
		3>&1 1>&2 2>&3)

	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$THIRDPARTY' function..."
		$THIRDPARTY
	else
		# Cancelled
		echo_message info "Installation of ${NAME,,} cancelled."
		main
	fi
}
