#!/bin/bash
#
# When adding (or removing) any functions remember to update
# the 'install_thirdparty' function below to reflect any changes you make

# Automatically import apps functions
function import_apps_functions {
	DIR="functions/apps"
	# iterate through the files in the 'functions/apps' folder
	for FUNCTION in ${SCRIPT_DIR}/$DIR/*; do
		if [[ -d $FUNCTION ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
			. $FUNCTION
		fi
	done
}

# Install Third-Party Applications
function install_thirdparty {
	NAME="Third-Party Software"
	echo_message title "Starting installation of ${NAME,,}..."
	import_apps_functions
	# Draw window
	THIRDPARTY=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhat ${NAME,,} would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
                'configure_bash'        'bash: Configure .bashrc .bash_aliases' \
		'install_emacs'         'emacs: Install emacs & helm' \
		'configure_emacs'       'emacs: Configure emacs & helm' \
		'install_i3'            'i3: Install i3 window manager' \
		'configure_i3'          'i3: Configure i3 window manager' \
		'install_fzf'           'fzf fuzzy finder' \
                'install_global'        'global: Install GNU global' \
                'install_python'        'python: Install Python' \
                'install_ietf_tools'    'ietf: Install IETF martinthomson toolchain & python virtualenv' \
                'install_docker'        'docker: Install latest stable version from docker apt repository' \
                'install_go'            'go: Install latest go version' \
                'configure_go'          'go: Configure env variables for go' \
                'install_gdb'           'gdb: Install gdb' \
                'install_firefox'       'firefox: Install firefox' \
                'configure_firefox'     'firefox: Configure firefox to work with i3' \
		'install_citx'          'japanese: Install japanese keyboard' \
                'install_polybox'       'polybox: Install ETHZ polybox' \
                'install_capnproto'     'cap n proto: Interchange format system' \
                'install_light'         'light: Install alternative to xbacklight for lenove laptop' \
                'install_umake'         'umake: Install ubuntu-make' \
                'install_pycharm'       'pycharm: Install pycharm python IDE' \
		3>&1 1>&2 2>&3)

    # 'install_chrome'        'Google Chrome' \
    # 'install_dropbox'       'Dropbox' \
    # 'install_oracle_java'   'Oracle Java' \
    # 'install_rvm'           'Ruby Version Manager (RVM)' \
    # 'install_sublime_text'  'Sublime Text 3' \

	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$THIRDPARTY' function..."
		$THIRDPARTY
	else
		# Cancelled
		echo_message info "Installation of ${NAME,,} cancelled."
		main
	fi
}
