#!/bin/bash

function extend_aliases {
    cp "${SCRIPT_DIR}/data/config/bash_aliases.in" ~/.bash_aliases_extended
    if ! grep -q '\. ~/\.bash_aliases_extended' ~/.bashrc; then
        cat >>~/.bashrc <<EOF
if [ -f ~/.bash_aliases_extended ]; then
    . ~/.bash_aliases_extended
fi
EOF
    fi
}

function configure_aliases {
    echo_message header "Setting .bash_aliases"
    keep_aliases="k"
    replace_aliases="r"
    extend_aliases="e"
    # Draw window
    CONFIG=$(eval `resize` && whiptail \
                                  --notags \
                                  --title "i3" \
                                  --menu "\nWhich configuration would you like to install?" \
                                  $LINES $COLUMNS $(( $LINES - 12 )) \
             "${keep_aliases}" "keep existing aliases" \
             "${replace_aliases}" "replace .bash_aliases" \
             "${extend_aliases}" "extend .bash_aliases" \
             3>&1 1>&2 2>&3)

    case "${CONFIG}" in
        "${keep_aliases}") echo_message info "Not modifying .bash_aliases"
                           ;;
        "${replace_aliases}") echo_message info "Replacing .bash_aliases"
                              cp "${SCRIPT_DIR}/data/config/bash_aliases.in" ~/.bash_aliases
                              ;;
        "${extend_aliases}") echo_message info "Extending .bash_aliases"
                             extend_aliases
                             ;;
    esac
}

function extend_bashrc {
    cp "${SCRIPT_DIR}/data/config/bashrc_extended.in" ~/.bashrc_extended
    if ! grep -q '\. ~/\.bashrc_extended' ~/.bashrc; then
        cat >>~/.bashrc <<EOF
if [ -f ~/.bashrc_extended ]; then
    . ~/.bashrc_extended
fi
EOF
    fi
}

function configure_bashrc {
    echo_message header "Setting .bashrc"
    keep_bashrc="k"
    replace_bashrc="r"
    extend_bashrc="e"
    # Draw window
    CONFIG=$(eval `resize` && whiptail \
                                  --notags \
                                  --title "i3" \
                                  --menu "\nWhich configuration would you like to install?" \
                                  $LINES $COLUMNS $(( $LINES - 12 )) \
             "${keep_bashrc}" "keep existing bashrc" \
             "${replace_bashrc}" "replace .bashrc" \
             "${extend_bashrc}" "extend .bashrc" \
             3>&1 1>&2 2>&3)

    case "${CONFIG}" in
        "${keep_bashrc}") echo_message info "Not modifying .bashrc"
                          ;;
        "${replace_bashrc}") echo_message info "Replacing .bashrc"
                             cp "${SCRIPT_DIR}/data/config/bashrc_basic.in" ~/.bashrc
                             extend_bashrc
                             ;;
        "${extend_bashrc}") echo_message info "Extending .bashrc without copying basic configurations"
                            extend_bashrc
                            ;;
    esac
}

function extend_profile {
    cp "${SCRIPT_DIR}/data/config/profile_extended.in" ~/.profile_extended
    if ! grep -q '\. ~/\.profile_extended' ~/.profile; then
        cat >>~/.profile <<EOF
if [ -f ~/.profile_extended ]; then
    . ~/.profile_extended
fi
EOF
    fi
}

function configure_profile {
    echo_message header "Setting .profile"
    keep_profile="k"
    replace_profile="r"
    extend_aliases="e"
    # Draw window
    CONFIG=$(eval `resize` && whiptail \
                                  --notags \
                                  --title "i3" \
                                  --menu "\nWhich configuration would you like to install?" \
                                  $LINES $COLUMNS $(( $LINES - 12 )) \
             "${keep_profile}" "keep existing profile" \
             "${replace_profile}" "replace .profile" \
             "${extend_profile}" "extend .profile" \
             3>&1 1>&2 2>&3)

    case "${CONFIG}" in
        "${keep_profile}") echo_message info "Not modifying .profile"
                           ;;
        "${replace_profile}") echo_message info "Replacing .profile"
                              cp "${SCRIPT_DIR}/data/config/profile_basic.in" ~/.profile
                              extend_profile
                              ;;
        "${extend_profile}") echo_message info "Extending .profile without copying basic configurations"
                             extend_profile
                             ;;
    esac
}

function configure_bash {
    configure_bashrc
    configure_aliases
    configure_profile
}
