#!/bin/bash

function install_docker {
    DOCKER_PPA_URL="https://download.docker.com/linux/ubuntu"
    DOCKER_PPA="deb [arch=amd64] $DOCKER_PPA_URL $(lsb_release -cs) stable"
    if ! grep -q "^deb .*$DOCKER_PPA_URL" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
        echo_message info "Downloading download.docker.com gpg keys"
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | superuser_do apt-key add -

        echo_message info "Add download.docker.com repository"
        sudo add-apt-repository "$DOCKER_PPA"
    else
        echo_message info "download.docker.com repository is already added"
    fi

    echo_message info "apt update"
    superuser_do apt update

    echo_message info "apt install docker"
    superuser_do apt install docker-ce

    echo_message info "Create docker group and add user"
    superuser_do groupadd docker
    superuser_do usermod -aG docker $USER
}
