#!/bin/bash

# emacs
function install_emacs {
	status="0"
	NAME="Emacs"
	while [ "$status" -eq 0 ]; do
		VERSION=$(eval `resize` && whiptail \
		--title "$NAME" \
		--radiolist "Which version of $NAME would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		"stable"    "Stable build" ON \
		"beta"      "Beta build" OFF \
		"unstable"  "Unstable build" OFF \
		3>&1 1>&2 2>&3) 
		# Change to lower case and remove spaces.
		case "${VERSION}" in
			stable)
				download_chrome stable;
			;;
			beta)
				download_chrome beta;
			;;
			unstable)
				download_chrome unstable;
			;;
			# return
			*) status=1 
				install_thirdparty
			;;
		esac
	done
}
