#!/bin/bash

# emacs
function install_emacs {
    DESIRED_EMACS_VERSION="emacs25"
    # if desired emacs version is not yet installed
    if [ $(check_package_installed ${DESIRED_EMACS_VERSION}) != 0 ]; then
        # remove existing emacs installations
        superuser_do "apt remove -y emacs emacs24*"

        # add repository for Emacs 25
        do_add_launchpad_ppa "Emacs 25" "kelleyk/emacs" ""

        # install Emacs 25
        superuser_do "apt install -y $DESIRED_EMACS_VERSION"
    fi

    cp -r "$SCRIPT_DIR/data/config/emacs/.emacs.d" ~
    [ -f ~/.emacs ] && rm ~/.emacs
    emacs --script "$SCRIPT_DIR/data/config/emacs/install.el"
}
