#!/bin/bash

function install_helm_fzf {
    git clone https://github.com/ibmandura/helm-fzf ~/.emacs.d/helm-fzf
}

#todo install fzf
# https://github.com/ibmandura/helm-fzf
# https://gist.github.com/bling/18655e86918bebd7bc3d
# https://stackoverflow.com/questions/36522834/vim-fuzzy-finder-like-for-emacs
# https://github.com/junegunn/fzf
# emacs
function install_emacs {
    DESIRED_EMACS_VERSION="emacs25"

    # remove existing emacs installations
    do_remove "emacs*"

    # if desired emacs version is not yet installed
    if [ $(check_package_installed ${DESIRED_EMACS_VERSION}) != 0 ]; then
        # add repository for Emacs 25
        do_add_launchpad_ppa "Emacs 25" "kelleyk/emacs" ""

        # install Emacs 25
        do_install "$DESIRED_EMACS_VERSION"
    fi

    # require fzf
    install_fzf
    install_helm_fzf
    install_global
}

function configure_emacs {
    cp -r "$SCRIPT_DIR/data/config/emacs/.emacs.d" ~
    [ -f ~/.emacs ] && rm ~/.emacs
    emacs --script "$SCRIPT_DIR/data/config/emacs/install.el"
}
