#!/bin/bash

function install_firefox {
    FIREFOX="firefox"
    # install firefox
    do_install "$FIREFOX"
}

function configure_firefox {
    (cd ~/.mozilla/firefox/*.default &&
    echo 'user_pref("browser.fullscreen.autohide","false");' >user.js)
}
